"""init_all_tables

Revision ID: 1b554b6956b8
Revises: 
Create Date: 2026-07-03 07:01:28.201974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b554b6956b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Назва компанії або проекту'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='Унікальний ключ для ідентифікації tenant'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Чи активний tenant'),
    sa.Column('description', sa.Text(), nullable=True, comment='Опис tenant (опціонально)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('trainers',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Telegram ID тренера'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='@username тренера в Telegram'),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Чи активний тренер'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainers_telegram_id'), 'trainers', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_trainers_tenant_id'), 'trainers', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='До якого tenant належить користувач'),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False, comment='Числовий ID користувача в Telegram'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='@username в Telegram (може бути відсутнім)'),
    sa.Column('full_name', sa.String(length=500), nullable=True, comment="Повне ім'я з Telegram профілю"),
    sa.Column('stage', sa.Enum('NEW', 'CONTACTED', 'INTERESTED', 'DEMO', 'CLIENT', name='user_stage'), nullable=False, comment='Поточна стадія в sales pipeline'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Чи активний користувач (не заблокував бота)'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Час останнього повідомлення від користувача'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('AI', 'HUMAN', name='conversation_mode'), nullable=False, comment='Хто зараз відповідає: AI чи тренер'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Чи активна розмова'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AI', 'TRAINER', 'SYSTEM', name='message_role'), nullable=False, comment='Хто написав повідомлення'),
    sa.Column('content', sa.Text(), nullable=False, comment='Текст повідомлення'),
    sa.Column('confidence', sa.Float(), nullable=True, comment='Впевненість AI у відповіді (0.0 - 1.0)'),
    sa.Column('need_human', sa.Boolean(), nullable=False, comment='Чи просить AI передати тренеру'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trainers_tenant_id'), table_name='trainers')
    op.drop_index(op.f('ix_trainers_telegram_id'), table_name='trainers')
    op.drop_table('trainers')
    op.drop_table('tenants')
    # ### end Alembic commands ###
